[2023-09-05T05:18:22.990+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: FIBA_dag.parse_data manual__2023-09-05T05:18:15.334038+00:00 [queued]>
[2023-09-05T05:18:22.996+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: FIBA_dag.parse_data manual__2023-09-05T05:18:15.334038+00:00 [queued]>
[2023-09-05T05:18:22.996+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-05T05:18:23.004+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): parse_data> on 2023-09-05 05:18:15.334038+00:00
[2023-09-05T05:18:23.009+0000] {standard_task_runner.py:57} INFO - Started process 973 to run task
[2023-09-05T05:18:23.011+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'FIBA_dag', 'parse_data', 'manual__2023-09-05T05:18:15.334038+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/FIBA.py', '--cfg-path', '/tmp/tmpoacne72n']
[2023-09-05T05:18:23.014+0000] {standard_task_runner.py:85} INFO - Job 182: Subtask parse_data
[2023-09-05T05:18:23.045+0000] {task_command.py:415} INFO - Running <TaskInstance: FIBA_dag.parse_data manual__2023-09-05T05:18:15.334038+00:00 [running]> on host 8ce2b8fabb21
[2023-09-05T05:18:23.096+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andy_hsu' AIRFLOW_CTX_DAG_ID='FIBA_dag' AIRFLOW_CTX_TASK_ID='parse_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-05T05:18:15.334038+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-05T05:18:15.334038+00:00'
[2023-09-05T05:18:23.456+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/FIBA.py", line 61, in parse_data
    left_point = m.find("table", class_ = 'points').find("div", class_ = 'score').find_all("span")[0].text.replace('\r\n','').strip()
AttributeError: 'NoneType' object has no attribute 'find_all'
[2023-09-05T05:18:23.530+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=FIBA_dag, task_id=parse_data, execution_date=20230905T051815, start_date=20230905T051822, end_date=20230905T051823
[2023-09-05T05:18:23.543+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 182 for task parse_data ('NoneType' object has no attribute 'find_all'; 973)
[2023-09-05T05:18:23.589+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-05T05:18:23.603+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
