[2023-09-11T06:37:31.693+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mlb_parser.data_clean manual__2023-09-11T06:37:29.667818+00:00 [queued]>
[2023-09-11T06:37:31.700+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mlb_parser.data_clean manual__2023-09-11T06:37:29.667818+00:00 [queued]>
[2023-09-11T06:37:31.702+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-11T06:37:31.712+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): data_clean> on 2023-09-11 06:37:29.667818+00:00
[2023-09-11T06:37:31.720+0000] {standard_task_runner.py:57} INFO - Started process 16581 to run task
[2023-09-11T06:37:31.724+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mlb_parser', 'data_clean', 'manual__2023-09-11T06:37:29.667818+00:00', '--job-id', '361', '--raw', '--subdir', 'DAGS_FOLDER/mlb_parser.py', '--cfg-path', '/tmp/tmpd0gv3kp2']
[2023-09-11T06:37:31.729+0000] {standard_task_runner.py:85} INFO - Job 361: Subtask data_clean
[2023-09-11T06:37:39.326+0000] {task_command.py:415} INFO - Running <TaskInstance: mlb_parser.data_clean manual__2023-09-11T06:37:29.667818+00:00 [running]> on host 2e8147b3a465
[2023-09-11T06:37:39.561+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andy_hsu' AIRFLOW_CTX_DAG_ID='mlb_parser' AIRFLOW_CTX_TASK_ID='data_clean' AIRFLOW_CTX_EXECUTION_DATE='2023-09-11T06:37:29.667818+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-11T06:37:29.667818+00:00'
[2023-09-11T06:37:39.589+0000] {logging_mixin.py:151} INFO - None
[2023-09-11T06:37:39.594+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mlb_parser.py", line 127, in main
    for t in team:
TypeError: 'NoneType' object is not iterable
[2023-09-11T06:37:39.614+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=mlb_parser, task_id=data_clean, execution_date=20230911T063729, start_date=20230911T063731, end_date=20230911T063739
[2023-09-11T06:37:39.642+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 361 for task data_clean ('NoneType' object is not iterable; 16581)
[2023-09-11T06:37:39.687+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-11T06:37:39.757+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
