[2023-09-11T06:28:12.014+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mlb_parser.select_team manual__2023-09-11T06:28:00.685596+00:00 [queued]>
[2023-09-11T06:28:12.021+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mlb_parser.select_team manual__2023-09-11T06:28:00.685596+00:00 [queued]>
[2023-09-11T06:28:12.022+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-11T06:28:12.035+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): select_team> on 2023-09-11 06:28:00.685596+00:00
[2023-09-11T06:28:12.042+0000] {standard_task_runner.py:57} INFO - Started process 15764 to run task
[2023-09-11T06:28:12.050+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mlb_parser', 'select_team', 'manual__2023-09-11T06:28:00.685596+00:00', '--job-id', '348', '--raw', '--subdir', 'DAGS_FOLDER/mlb_parser.py', '--cfg-path', '/tmp/tmpxj9jq_2b']
[2023-09-11T06:28:12.055+0000] {standard_task_runner.py:85} INFO - Job 348: Subtask select_team
[2023-09-11T06:28:12.133+0000] {task_command.py:415} INFO - Running <TaskInstance: mlb_parser.select_team manual__2023-09-11T06:28:00.685596+00:00 [running]> on host 2e8147b3a465
[2023-09-11T06:28:12.209+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andy_hsu' AIRFLOW_CTX_DAG_ID='mlb_parser' AIRFLOW_CTX_TASK_ID='select_team' AIRFLOW_CTX_EXECUTION_DATE='2023-09-11T06:28:00.685596+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-11T06:28:00.685596+00:00'
[2023-09-11T06:28:12.213+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mlb_parser.py", line 32, in select_team
    ti.xcom_push(key = 'team_parsered', values = ['nationals', 'braves', 'mets', 'marlins', 'phillies'])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_push() got an unexpected keyword argument 'values'
[2023-09-11T06:28:12.232+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=mlb_parser, task_id=select_team, execution_date=20230911T062800, start_date=20230911T062812, end_date=20230911T062812
[2023-09-11T06:28:12.241+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 348 for task select_team (xcom_push() got an unexpected keyword argument 'values'; 15764)
[2023-09-11T06:28:12.261+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-11T06:28:12.276+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
